WIP! Upgrade ES to 5.1.1
UKHomeOffice/docker-elasticsearch pull request #23
Opened 2016-12-20 12:02 UTC by marcinc

This PR:
* Bumps ES to latest 5.1.1
* Removes elasticsearch-HQ as ES 5.x doesn't run site plugins. Possible to add that as standalone later.
* Changes ES / logging configuration
* `ES_HEAP_SIZE` deprecated, now `ELASTIC_SEARCH_HEAP_SIZE`. Heap size set via `ES_JAVA_OPTS`

2016-12-20 13:38 UTC, jits commented on Dockerfile
> -RUN /elasticsearch/bin/plugin install royrusso/elasticsearch-HQ/v2.0.3
Could replace this with [kopf](https://github.com/lmenezes/elasticsearch-kopf)?

2016-12-20 13:38 UTC, jits commented on Dockerfile
> -RUN /elasticsearch/bin/plugin install royrusso/elasticsearch-HQ/v2.0.3
Although, doesn't look like kopf supports the latest Elastic stack.

2016-12-30 16:09 UTC, vaijab requested changes

2016-12-30 16:09 UTC, vaijab commented on README.md
> +### Elasticsearch Index configuration
Not really needed, because this is documented in ES docs and irrelevant here.

2016-12-30 16:09 UTC, vaijab commented on config/log4j2.properties
> +status = error
Did you make any changes to this file or is the same that ES ships already?

What we want is less verbose logging and to console only.

2016-12-30 16:09 UTC, vaijab commented on run.sh
> +export ELASTIC_SEARCH_HEAP_SIZE=${ELASTIC_SEARCH_HEAP_SIZE:=450m}
What's the point in renaming the env var?

2016-12-30 16:09 UTC, vaijab commented on run.sh
> +chmod +r /elasticsearch/config/log4j2.properties /elasticsearch/config/elasticsearch.yml
What's that?

2016-12-30 16:22 UTC, marcinc commented on run.sh
> +export ELASTIC_SEARCH_HEAP_SIZE=${ELASTIC_SEARCH_HEAP_SIZE:=450m}
`ES_HEAP_SIZE` is no longer supported and ES complaints about it as head size is now set via java opts. Renamed to keep it separately configurable.

2016-12-30 16:23 UTC, marcinc commented on README.md
> +### Elasticsearch Index configuration
Will remove.

2016-12-30 16:24 UTC, vaijab commented on run.sh
> +export ELASTIC_SEARCH_HEAP_SIZE=${ELASTIC_SEARCH_HEAP_SIZE:=450m}
Ah cool. This time they check that the world is correct :-)

2016-12-30 16:28 UTC, marcinc commented on config/log4j2.properties
> +status = error
It's new default logging configuration shipped with ES 5.x. I'll have a look how to reduce logging here.

2016-12-30 16:50 UTC, vaijab commented on config/log4j2.properties
> +status = error
If we don't change anything then we should not add this file.

2016-12-30 17:40 UTC, marcinc commented on run.sh
> +chmod +r /elasticsearch/config/log4j2.properties /elasticsearch/config/elasticsearch.yml
Early testing artifact... Removing.

2016-12-30 18:27 UTC, marcinc commented on config/log4j2.properties
> +status = error
It's been slightly modified but I reduced it to only log to console. Now using official docker  image configuration (https://github.com/docker-library/elasticsearch/blob/1107caed5c403a63d99c1b1ae1f7002d387c7e85/5/config/log4j2.properties).

2016-12-30 18:29 UTC, vaijab approved these changes

2017-01-05 11:54 UTC, merged